import { APIGatewayProxyWithCognitoAuthorizerEvent } from 'aws-lambda'

export const getUserIdFromEvent = (event: APIGatewayProxyWithCognitoAuthorizerEvent): string => {
  // Using username as the user id because it is not a login method, but a UUID generated by cognito
  // https://stackoverflow.com/questions/39223347/should-i-use-aws-cognito-username-or-sub-uid-for-storing-in-database
  const userId = event.requestContext.authorizer.claims?.['cognito:username']

  if (!userId) throw new Error('Could not find user id in the event')
  return userId
}
